### ISSUE TITLE
//MARK: Lazy Load 改成 #pragma mark - LazyLoad 会不会好点

### ISSUE THREAD

**Issue by LONGHEIHEI** [iDevOrz/JYLazyLoader#2]
![image](https://user-images.githubusercontent.com/29967080/62842145-7995c500-bce2-11e9-97db-79d94742bb20.png)
![image](https://user-images.githubusercontent.com/29967080/62842149-7f8ba600-bce2-11e9-9466-0716424934ba.png)

**Comment by iDevOrz** [comment]
``//MARK: `` 一样可以把代码分割成逻辑区块。和 ``#pragma mark ``其实没差，但是 ``//MARK: `` 在 Objective-C和 Swift都可用，但是  ``#pragma mark `` 只能用于前者。只是一个习惯问题。
