### ISSUE TITLE
macOS 11.3.1,Xcode 12.5 无法使用了

### ISSUE THREAD

**Issue by Mr9468** [iDevOrz/JYLazyLoader#3]
macOS 11.3.1,Xcode 12.5 无法使用了,是否不支持最新的 Xcode 和 macOS

**Comment by dahhd** [comment]
同 Xcode 12.5 无法使用了，添加扩展后，Xcode 里已经找不到了。

**Comment by dahhd** [comment]
@Mr9468 我fork 了一份，修复了Xcode 12.5 失效的问题，已经提交 pull Request，如果着急的话可以先用我的：https://github.com/dahhd/JYLazyLoader.git

**Comment by iDevOrz** [comment]
Should be fixed now as of [``1.0.2``](https://github.com/iDevOrz/JYLazyLoader/tree/1.0.2) , please let me know if it's not. Thanks for raising this.
